= История №2: Компьютерное время
Выполнил работу: Касимов Роман Эльмирович, ст. гр. Б22-515

== Описание лабораторного стенда

=== Описание используемой рабочей среды
* Процессор: Intel(R) Core(TM) i3-10110U CPU, 2.10GHz, 2 ядра, 4 логических процессора
* Установленная оперативная память (RAM): 8Gi.
* Тип памяти: DRAM 
* Операционная система: Ubuntu 24.04 LTS
* Компилятор: g++(gcc) 13.3.0
* Язык программирования: c

== Теоретические вопросы
. Структуры данных для хранения меток времени
** Язык C:
... struct timespec (наносекундная точность)
... struct timeval (микросекундная точность)
... struct __timespec64 (аналог timespec с поддержкой времени после 2038 года)
... time_t
... tm (в основном для календарных операций)
** Язык C++
... std::chrono 
. Часы реального времени в Linux
В файловой системе ОС linux часы реального времени представленны симлинком _/dev/rtc_ на _rtc0_

=== Использование rtc в файловой системе
image1::../images/rtc.png[Файловая система]

Для работы с часами можно использовать файлы _date_, _time_, _since_epoch_, позволяющие узнать текущие дату, время и количество секунд UNIX времени соответсвенно
Также доступна утилита командной строки _hwclock_

=== Использование утилиты hwclock
image2::../images/hwclock.png[Клоки]
