= История №3: SQLite3
Выполнил работу: Касимов Роман Эльмирович, ст. гр. Б22-515

== Описание лабораторного стенда

=== Описание используемой рабочей среды
* Процессор: Intel(R) Core(TM) i3-10110U CPU, 2.10GHz, 2 ядра, 4 логических процессора
* Установленная оперативная память (RAM): 8Gi.
* Тип памяти: DRAM 
* Операционная система: Ubuntu 24.04 LTS
* Компилятор: g++(gcc) 13.3.0
* Язык программирования: c++

== Диаграммы сравнения производительности
Предметная область: структура итало-американской https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%84%D0%B8%D1%8F[мафии] 

С помощью команды
[source, pikchr]
----
N0: box "Boss" fit at (5, 0)

N1: box "Consigliere" fit at (3, -1)
N2: box "Underboss" fit at (7, -1)

N3: box "Capo 1" fit at (2, -2)
N4: box "Capo 2" fit at (4, -2)
N5: box "Capo 3" fit at (6, -2)
N6: box "Capo 4" fit at (8, -2)

N7: box "Soldier 1" fit at (1.5, -3)
N8: box "Soldier 2" fit at (2.5, -3)
N9: box "Soldier 3" fit at (3.5, -3)
N10: box "Soldier 4" fit at (4.5, -3)
N11: box "Soldier 5" fit at (5.5, -3)
N12: box "Soldier 6" fit at (6.5, -3)
N13: box "Soldier 7" fit at (7.5, -3)
N14: box "Soldier 8" fit at (8.5, -3)

N15: box "Associate" fit at (2, -4)
N16: box "Associate" fit at (3, -4)
N17: box "Associate" fit at (4, -4)
N18: box "Associate" fit at (5, -4)
N19: box "Associate" fit at (6, -4)
N20: box "Associate" fit at (7, -4)

arrow from N0.s to N1.n
arrow from N0.s to N2.n

arrow from N2.s to N3.n
arrow from N2.s to N4.n
arrow from N2.s to N5.n
arrow from N2.s to N6.n

arrow from N3.s to N7.n
arrow from N3.s to N8.n

arrow from N4.s to N9.n
arrow from N4.s to N10.n

arrow from N5.s to N11.n
arrow from N5.s to N12.n

arrow from N6.s to N13.n
arrow from N6.s to N14.n

arrow from N7.s to N15.n
arrow from N8.s to N16.n
arrow from N9.s to N17.n
arrow from N10.s to N18.n
arrow from N11.s to N19.n
arrow from N12.s to N20.n
----

Текстовый файл (генерируемый программой)
[source, c++]
----
// ├───Boss
// │   ├───Consigliere
// │   └───Underboss
// │       ├───Capo1
// |       |   ├───Soldier1
// |       |   |        Asocciate
// │       |   └───Soldier2
// |       |            Asocciate
// |       ├───Capo2
// |       |   ├───Soldier1
// |       |   |        Asocciate
// │       |   └───Soldier2
// |       |            Asocciate    
// |       ├───Capo3
// |       |   ├───Soldier1
// |       |   |        Asocciate
// │       |   └───Soldier2
// |       |            Asocciate
// |       └───Capo4
// |           ├───Soldier1
// │           └───Soldier2
----

== Результаты эксперимента

=== Полученные результаты записи данных:
[cols = 2]
|====
|Критери1
|Значение

|Суммарный объем входных данных txt
|10,5 МБ

|Объем pikchr файлов
|22.3 МБ

|Объем svg файлов
|176,6 МБ

|Соотношение объема выходных данных к входным
|7.9

|Среднее время генерации одной диаграммы
|592 мкс

|Среднее время обработки 1 байта входа
|8618 нс
|====

== Выводы
В ходе выполнения лабораторной работы была изучена система описания векторной графики pikchr и её синтаксис. Была разработана программа на языке C++, реализующая генерацию текстовых файлов, представляющих собой структуру итальянской мафии. Программа также осуществляет генерацию pikchr-кода для визуализации сгенерированных структур. В результате были сгенерированы входные данные общим объёмом 10 МБ, итоговый объём pikchr-файлов — 22,3 МБ, а сгенерированных SVG-файлов — более 176,6 МБ. Таким образом, визуальное представление данных оказалось в 7.9 раза объёмнее, чем текстовое описание на pikchr. Среднее время генерации одной диаграммы составило около 0.6 мс, а обработка одного байта входных данных в среднем занимала 7 мкс.