= История №3: SQLite3
Выполнил работу: Касимов Роман Эльмирович, ст. гр. Б22-515

== Описание лабораторного стенда

=== Описание используемой рабочей среды
* Процессор: Intel(R) Core(TM) i3-10110U CPU, 2.10GHz, 2 ядра, 4 логических процессора
* Установленная оперативная память (RAM): 8Gi.
* Тип памяти: DRAM 
* Операционная система: Ubuntu 24.04 LTS
* Компилятор: g++(gcc) 13.3.0
* Язык программирования: c++

== Диаграммы сравнения производительности
Предметная область: структура итало-американской https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%84%D0%B8%D1%8F[мафии] 

С помощью команды

++++
<style>
  .hidden {
     position: absolute !important;
     opacity: 0 !important;
     pointer-events: none !important;
     display: none !important;
  }
</style>
<script>
  function toggleHidden(id){
    for(var c of document.getElementById(id).children){
      c.classList.toggle('hidden');
    }
  }
</script>
<meta charset="utf-8">
</head>
<body>
<div id="svg-1" onclick="toggleHidden('svg-1')">
<div style='border:3px solid lightgray;max-width:1033px;'>
<svg xmlns='http://www.w3.org/2000/svg' style='font-size:initial;' class="pikchr" viewBox="0 0 1033.57 466.56" data-pikchr-date="20250321215505">
<path d="M314.122,32.4L362.16,32.4L362.16,2.16L314.122,2.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="338.141" y="17.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">lab1</text>
<path d="M39.1392,176.4L61.1424,176.4L61.1424,146.16L39.1392,146.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="50.1408" y="161.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">1</text>
<path d="M2.16,320.4L98.1216,320.4L98.1216,290.16L2.16,290.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="50.1408" y="305.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">page.html</text>
<path d="M327.139,176.4L349.142,176.4L349.142,146.16L327.139,146.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="338.141" y="161.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">2</text>
<path d="M218.16,320.4L314.122,320.4L314.122,290.16L218.16,290.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="266.141" y="305.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">page.html</text>
<path d="M370.512,320.4L449.77,320.4L449.77,290.16L370.512,290.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="410.141" y="305.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">script.js</text>
<path d="M615.139,176.4L637.142,176.4L637.142,146.16L615.139,146.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="626.141" y="161.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">3</text>
<path d="M506.16,320.4L602.122,320.4L602.122,290.16L506.16,290.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="554.141" y="305.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">page.html</text>
<path d="M685.354,320.4L710.928,320.4L710.928,290.16L685.354,290.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="698.141" y="305.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">js</text>
<path d="M214.301,464.4L317.981,464.4L317.981,434.16L214.301,434.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="266.141" y="449.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">brackets.js</text>
<path d="M353.174,464.4L467.107,464.4L467.107,434.16L353.174,434.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="410.141" y="449.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">deepCopy.js</text>
<path d="M518.026,464.4L590.256,464.4L590.256,434.16L518.026,434.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="554.141" y="449.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">main.js</text>
<path d="M651.83,464.4L744.451,464.4L744.451,434.16L651.83,434.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="698.141" y="449.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">median.js</text>
<path d="M782.986,464.4L901.296,464.4L901.296,434.16L782.986,434.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="842.141" y="449.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">remainder.js</text>
<path d="M940.867,464.4L1031.41,464.4L1031.41,434.16L940.867,434.16Z"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<text x="986.141" y="449.28" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">sorting.js</text>
<polygon points="50.1408,146.16 59.2682,137.91 62.4423,145.946" style="fill:rgb(0,0,0)"/>
<path d="M338.141,32.4L55.498,144.044"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="338.141,146.16 333.821,134.64 342.461,134.64" style="fill:rgb(0,0,0)"/>
<path d="M338.141,32.4L338.141,140.4"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="626.141,146.16 613.839,145.946 617.013,137.91" style="fill:rgb(0,0,0)"/>
<path d="M338.141,32.4L620.784,144.044"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="50.1408,290.16 45.8208,278.64 54.4608,278.64" style="fill:rgb(0,0,0)"/>
<path d="M50.1408,176.4L50.1408,284.4"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="266.141,290.16 268.651,278.116 275.952,282.736" style="fill:rgb(0,0,0)"/>
<path d="M338.141,176.4L269.221,285.293"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="410.141,290.16 400.33,282.736 407.63,278.116" style="fill:rgb(0,0,0)"/>
<path d="M338.141,176.4L407.06,285.293"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="554.141,290.16 556.651,278.116 563.952,282.736" style="fill:rgb(0,0,0)"/>
<path d="M626.141,176.4L557.221,285.293"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="698.141,290.16 688.33,282.736 695.63,278.116" style="fill:rgb(0,0,0)"/>
<path d="M626.141,176.4L695.06,285.293"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="266.141,434.16 276.181,427.049 278.381,435.404" style="fill:rgb(0,0,0)"/>
<path d="M698.141,320.4L271.711,432.693"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="410.141,434.16 419.268,425.91 422.442,433.946" style="fill:rgb(0,0,0)"/>
<path d="M698.141,320.4L415.498,432.044"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="554.141,434.16 560.502,423.629 565.858,430.409" style="fill:rgb(0,0,0)"/>
<path d="M698.141,320.4L558.661,430.589"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="698.141,434.16 693.821,422.64 702.461,422.64" style="fill:rgb(0,0,0)"/>
<path d="M698.141,320.4L698.141,428.4"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="842.141,434.16 830.423,430.409 835.779,423.629" style="fill:rgb(0,0,0)"/>
<path d="M698.141,320.4L837.621,430.589"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
<polygon points="986.141,434.16 973.839,433.946 977.013,425.91" style="fill:rgb(0,0,0)"/>
<path d="M698.141,320.4L980.784,432.044"  style="fill:none;stroke-width:2.16;stroke:rgb(0,0,0);" />
</svg>
</div>
<pre class='hidden'>
N0: box "lab1" fit at (4, 0)

N1: box "1" fit at (2, -1)
N2: box "page.html" fit at (2, -2)

N3: box "2" fit at (4, -1)
N4: box "page.html" fit at (3.5, -2)
N5: box "script.js" fit at (4.5, -2)

N6: box "3" fit at (6, -1)
N7: box "page.html" fit at (5.5, -2)
N8: box "js" fit at (6.5, -2)
N9: box "brackets.js" fit at (3.5, -3)
N10: box "deepCopy.js" fit at (4.5, -3)
N11: box "main.js" fit at (5.5, -3)
N12: box "median.js" fit at (6.5, -3)
N13: box "remainder.js" fit at (7.5, -3)
N14: box "sorting.js" fit at (8.5, -3)

arrow from N0.s to N1.n
arrow from N0.s to N3.n
arrow from N0.s to N6.n

arrow from N1.s to N2.n

arrow from N3.s to N4.n
arrow from N3.s to N5.n

arrow from N6.s to N7.n
arrow from N6.s to N8.n

arrow from N8.s to N9.n
arrow from N8.s to N10.n
arrow from N8.s to N11.n
arrow from N8.s to N12.n
arrow from N8.s to N13.n
arrow from N8.s to N14.n
</pre>
</div>
++++

Текстовый файл (генерируемый программой)
[source, c++]
----
// ├───Boss
// │   ├───Consigliere
// │   └───Underboss
// │       ├───Capo1
// |       |   ├───Soldier1
// |       |   |        Asocciate
// │       |   └───Soldier2
// |       |            Asocciate
// |       ├───Capo2
// |       |   ├───Soldier1
// |       |   |        Asocciate
// │       |   └───Soldier2
// |       |            Asocciate    
// |       ├───Capo3
// |       |   ├───Soldier1
// |       |   |        Asocciate
// │       |   └───Soldier2
// |       |            Asocciate
// |       └───Capo4
// |           ├───Soldier1
// │           └───Soldier2
----

== Результаты эксперимента

=== Полученные результаты записи данных:
[cols = 2]
|====
|Критери1
|Значение

|Суммарный объем входных данных txt
|10,5 МБ

|Объем pikchr файлов
|22.3 МБ

|Объем svg файлов
|176,6 МБ

|Соотношение объема выходных данных к входным
|7.9

|Среднее время генерации одной диаграммы
|592 мкс

|Среднее время обработки 1 байта входа
|8618 нс
|====

== Выводы
В ходе выполнения лабораторной работы была изучена система описания векторной графики pikchr и её синтаксис. Была разработана программа на языке C++, реализующая генерацию текстовых файлов, представляющих собой структуру итальянской мафии. Программа также осуществляет генерацию pikchr-кода для визуализации сгенерированных структур. В результате были сгенерированы входные данные общим объёмом 10 МБ, итоговый объём pikchr-файлов — 22,3 МБ, а сгенерированных SVG-файлов — более 176,6 МБ. Таким образом, визуальное представление данных оказалось в 7.9 раза объёмнее, чем текстовое описание на pikchr. Среднее время генерации одной диаграммы составило около 0.6 мс, а обработка одного байта входных данных в среднем занимала 7 мкс.